### ISSUE TITLE
key with empty value not parsed correctly

### ISSUE THREAD

**Issue by sayMuFaSa** [justinmk/tree-sitter-ini#9]
When the value of a key is empty, I mean if after equal sign there is nothing but line break, whatever goes next is not highlighted properly.

**Comment by sayMuFaSa** [comment]
Like here. Section 2 is not highlighted at all.
![2024-07-27_00-18](https://github.com/user-attachments/assets/abf1548c-261b-4244-9b2a-4523b2d585c9)

**Comment by justinmk** [comment]
Based on https://stackoverflow.com/a/9491779/152142 it seems like a "null value" is allowed. So this is a bug.
